### PR TITLE
Swift4.2

### PR DESCRIPTION
**Pull request by jaimeeee**

### CODE REVIEW

**Comment by koogawa** [comment]
@jaimeeee Thank you for the notice. 👍

**Comment by jaimeeee** [comment]
@koogawa no problem! Great library by the way :) However, the `.podspec` still needs to be updated, isn't it?

**Comment by koogawa** [comment]
@jaimeeee Yes! I updated `.podspec` https://github.com/koogawa/FoursquareAPIClient/commit/469e18dd105f02273fbc8c503595cf2cebe7a51d

**Comment by jaimeeee** [comment]
Awesome! Thank you so much!

**Pull request merged**
